# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9a8541b857aef946f1ebd98589d5f4af5c0ef4f8200ca5a26f764beb407c08fdb2759140f95407d6c7405d87fcf2fc6d7c09c5e15cfc7a3b7ef57464a590c2b

test:
  secret_key_base: b1fa6a9b8950fcbc71546adf1f37fdb65cff4d5503345426ed373c6526a777b27e6be10aafd1ab0b87bc4c1264c3d96200220c28684b7492db9779de90068117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
